-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "ssamembers_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ssamembers_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"url" varchar(1024) NOT NULL,
	"tag" varchar(256) DEFAULT 'General',
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ssamembers_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ssamembers_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"imageUrl" varchar(1024) DEFAULT 'https://ba961nquml.ufs.sh/f/8WZL3qQlnrib7eKeL1A2EOHTiwGzyx0cWs9IqK7hPnj3YaLU',
	"location" varchar(256) NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"endDate" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ssamembers_rsvp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ssamembers_rsvp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "unique_rsvp_per_event" UNIQUE("eventId","email")
);
--> statement-breakpoint
ALTER TABLE "ssamembers_rsvp" ADD CONSTRAINT "ssamembers_rsvp_eventId_ssamembers_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."ssamembers_event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "links_name_idx" ON "ssamembers_link" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "events_name_idx" ON "ssamembers_event" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "rsvp_event_id_idx" ON "ssamembers_rsvp" USING btree ("eventId" int4_ops);
*/